all: TreesAndGraphs

TreesAndGraphs: TreesAndGraphs.o
	g++ -Wall -std=c++11 TreesAndGraphs.o -o TreesAndGraphs

TreesAndGraphs.o: TreesAndGraphs.cpp
	g++ -Wall -std=c++11 -c TreesAndGraphs.cpp -o TreesAndGraphs.o
