all: StacksAndQueues

StacksAndQueues: StacksAndQueues.o
	g++ -Wall -std=c++11 StacksAndQueues.o -o StacksAndQueues

StacksAndQueues.o: StacksAndQueues.cpp
	g++ -Wall -std=c++11 -c StacksAndQueues.cpp -o StacksAndQueues.o
