all: ObjectOrientedDesign

ObjectOrientedDesign: ObjectOrientedDesign.o
	g++ -Wall -std=c++11 ObjectOrientedDesign.o -o ObjectOrientedDesign

ObjectOrientedDesign.o: ObjectOrientedDesign.cpp
	g++ -Wall -std=c++11 -c ObjectOrientedDesign.cpp -o ObjectOrientedDesign.o
