all: ArraysAndStrings

ArraysAndStrings: ArraysAndStrings.o
	g++ -Wall -std=c++11 ArraysAndStrings.o -o ArraysAndStrings

ArraysAndStrings.o: ArraysAndStrings.cpp
	g++ -Wall -std=c++11 -c ArraysAndStrings.cpp -o ArraysAndStrings.o
