all: BitManipulation

BitManipulation: BitManipulation.o
	g++ -Wall -std=c++11 BitManipulation.o -o BitManipulation

BitManipulation.o: BitManipulation.cpp
	g++ -Wall -std=c++11 -c BitManipulation.cpp -o BitManipulation.o
